I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 24, in script call
    call show_my_available_protectors(False)
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 24, in script call
    call show_my_available_protectors(False)
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 13, in script
    menu:
  File "game/screens.rpy", line 2393, in execute
    screen protector_evolution_choosing_screen(my_protector):
  File "game/screens.rpy", line 2393, in execute
    screen protector_evolution_choosing_screen(my_protector):
  File "game/screens.rpy", line 2394, in execute
    frame:
  File "game/screens.rpy", line 2400, in execute
    fixed:
  File "game/screens.rpy", line 2414, in execute
    hbox:
  File "game/screens.rpy", line 2418, in execute
    vbox:
  File "game/screens.rpy", line 2429, in execute
    $ orig_width, orig_height = renpy.image_size(show_protectors_image)
  File "game/screens.rpy", line 2429, in <module>
    $ orig_width, orig_height = renpy.image_size(show_protectors_image)
                                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Couldn't find file 'images/protectors/Robot/5_1.png'.

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 24, in script call
    call show_my_available_protectors(False)
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 24, in script call
    call show_my_available_protectors(False)
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 13, in script
    menu:
  File "renpy/ast.py", line 1815, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
             ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/exports/menuexports.py", line 135, in menu
    rv = renpy.store.menu(new_items)
         ~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "renpy/exports/menuexports.py", line 418, in display_menu
    rv = renpy.ui.interact(mouse="menu", type=type, roll_forward=roll_forward)
         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/ui.py", line 304, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/core.py", line 2219, in interact
    repeat, rv = self.interact_core(
                 ~~~~~~~~~~~~~~~~~~^
        preloads=preloads,
        ^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )  # type: ignore
    ^                
  File "renpy/display/core.py", line 2757, in interact_core
    root_widget.visit_all(lambda d: d.per_interact())
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/displayable.py", line 432, in visit_all
    d.visit_all(callback, seen)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "renpy/display/displayable.py", line 432, in visit_all
    d.visit_all(callback, seen)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "renpy/display/displayable.py", line 432, in visit_all
    d.visit_all(callback, seen)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "renpy/display/screen.py", line 503, in visit_all
    callback(self)
    ~~~~~~~~^^^^^^
  File "renpy/display/core.py", line 2757, in <lambda>
    root_widget.visit_all(lambda d: d.per_interact())
                                    ~~~~~~~~~~~~~~^^ 
  File "renpy/display/screen.py", line 514, in per_interact
    self.update()
    ~~~~~~~~~~~^^
  File "renpy/display/screen.py", line 715, in update
    self.screen.function(**self.scope)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "game/screens.rpy", line 2393, in execute
    screen protector_evolution_choosing_screen(my_protector):
  File "game/screens.rpy", line 2393, in execute
    screen protector_evolution_choosing_screen(my_protector):
  File "game/screens.rpy", line 2394, in execute
    frame:
  File "game/screens.rpy", line 2400, in execute
    fixed:
  File "game/screens.rpy", line 2414, in execute
    hbox:
  File "game/screens.rpy", line 2418, in execute
    vbox:
  File "game/screens.rpy", line 2429, in execute
    $ orig_width, orig_height = renpy.image_size(show_protectors_image)
  File "game/screens.rpy", line 2429, in <module>
    $ orig_width, orig_height = renpy.image_size(show_protectors_image)
                                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/exports/displayexports.py", line 771, in image_size
    surf = im.load()
           ~~~~~~~^^
  File "renpy/display/im.py", line 838, in load
    raise e
  File "renpy/display/im.py", line 792, in load
    filelike = renpy.loader.load(self.filename, directory="images")
               ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/loader.py", line 698, in load
    raise FileNotFoundError("Couldn't find file '%s'." % name)
FileNotFoundError: Couldn't find file 'images/protectors/Robot/5_1.png'.

Windows-11-10.0.26120-SP0 AMD64
Ren'Py 8.4.1.25072401
Protectors 1.0
Mon Sep 22 21:52:44 2025
