I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 26, in script call
    call show_my_available_protectors(False)
  File "game/places.rpy", line 28, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/resting.rpy", line 4, in script
    python:
  File "game/resting.rpy", line 7, in <module>
    mission.updateDaysPassed()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "game/classes.rpy", line 159, in updateDaysPassed
    self.finishMission()
    ~~~~~~~~~~~~~~~~~~^^
  File "game/classes.rpy", line 183, in finishMission
    my_protectors_map[self.assignedProtectorName].increasing_xp(self.xp_received * self.daysPassed)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/classes.rpy", line 50, in increasing_xp
    renpy(mc, "Are we going to have a promotion?")
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/places.rpy", line 18, in script call
    call base_travel_menu()
  File "game/places.rpy", line 26, in script call
    call show_my_available_protectors(False)
  File "game/places.rpy", line 28, in script call
    call base_travel_menu()
  File "game/places.rpy", line 36, in script call
    call rest()
  File "game/resting.rpy", line 4, in script
    python:
  File "renpy/ast.py", line 1187, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1260, in py_exec_bytecode
    exec(bytecode, globals, locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/resting.rpy", line 7, in <module>
    mission.updateDaysPassed()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "game/classes.rpy", line 159, in updateDaysPassed
    self.finishMission()
    ~~~~~~~~~~~~~~~~~~^^
  File "game/classes.rpy", line 183, in finishMission
    my_protectors_map[self.assignedProtectorName].increasing_xp(self.xp_received * self.daysPassed)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/classes.rpy", line 50, in increasing_xp
    renpy(mc, "Are we going to have a promotion?")
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable

Windows-11-10.0.26120-SP0 AMD64
Ren'Py 8.4.1.25072401
Protectors 1.0
Fri Aug  8 00:07:42 2025
