I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 7, in script call
    call check_online_shop()
  File "game/base_of_operations.rpy", line 74, in script
    call screen online_shop()
  File "game/screens.rpy", line 3211, in execute
    screen online_shop():
  File "game/screens.rpy", line 3211, in execute
    screen online_shop():
  File "game/screens.rpy", line 3231, in execute
    frame:
  File "game/screens.rpy", line 3259, in execute
    vbox:
  File "game/screens.rpy", line 3339, in execute
    if online_shop_show == "show_equipments":
  File "game/screens.rpy", line 3341, in execute
    hbox:
  File "game/screens.rpy", line 3345, in execute
    for rarity, equipments in online_shop_variable.selling_equipments_list.items():
  File "game/screens.rpy", line 3346, in execute
    if rarity == rarity_selected:
  File "game/screens.rpy", line 3347, in execute
    for equipment in equipments:
  File "game/screens.rpy", line 3364, in execute
    $ orig_width, orig_height = renpy.image_size(equipment_img)
  File "game/screens.rpy", line 3364, in <module>
    $ orig_width, orig_height = renpy.image_size(equipment_img)
                                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
FileNotFoundError: Couldn't find file 'images/equipments/Miracle_boots.png'.

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 7, in script call
    call check_online_shop()
  File "game/base_of_operations.rpy", line 74, in script
    call screen online_shop()
  File "renpy/ast.py", line 2231, in execute
    self.call("execute")
    ~~~~~~~~~^^^^^^^^^^^
  File "renpy/ast.py", line 2195, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/statements.py", line 379, in call
    return method(parsed, *args, **kwargs)
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/common/000statements.rpy", line 695, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/exports/statementexports.py", line 348, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/ui.py", line 304, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/core.py", line 2219, in interact
    repeat, rv = self.interact_core(
                 ~~~~~~~~~~~~~~~~~~^
        preloads=preloads,
        ^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )  # type: ignore
    ^                
  File "renpy/display/core.py", line 2757, in interact_core
    root_widget.visit_all(lambda d: d.per_interact())
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/displayable.py", line 432, in visit_all
    d.visit_all(callback, seen)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "renpy/display/displayable.py", line 432, in visit_all
    d.visit_all(callback, seen)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "renpy/display/displayable.py", line 432, in visit_all
    d.visit_all(callback, seen)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "renpy/display/screen.py", line 503, in visit_all
    callback(self)
    ~~~~~~~~^^^^^^
  File "renpy/display/core.py", line 2757, in <lambda>
    root_widget.visit_all(lambda d: d.per_interact())
                                    ~~~~~~~~~~~~~~^^ 
  File "renpy/display/screen.py", line 514, in per_interact
    self.update()
    ~~~~~~~~~~~^^
  File "renpy/display/screen.py", line 715, in update
    self.screen.function(**self.scope)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "game/screens.rpy", line 3211, in execute
    screen online_shop():
  File "game/screens.rpy", line 3211, in execute
    screen online_shop():
  File "game/screens.rpy", line 3231, in execute
    frame:
  File "game/screens.rpy", line 3259, in execute
    vbox:
  File "game/screens.rpy", line 3339, in execute
    if online_shop_show == "show_equipments":
  File "game/screens.rpy", line 3341, in execute
    hbox:
  File "game/screens.rpy", line 3345, in execute
    for rarity, equipments in online_shop_variable.selling_equipments_list.items():
  File "game/screens.rpy", line 3346, in execute
    if rarity == rarity_selected:
  File "game/screens.rpy", line 3347, in execute
    for equipment in equipments:
  File "game/screens.rpy", line 3364, in execute
    $ orig_width, orig_height = renpy.image_size(equipment_img)
  File "game/screens.rpy", line 3364, in <module>
    $ orig_width, orig_height = renpy.image_size(equipment_img)
                                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "renpy/exports/displayexports.py", line 771, in image_size
    surf = im.load()
           ~~~~~~~^^
  File "renpy/display/im.py", line 838, in load
    raise e
  File "renpy/display/im.py", line 792, in load
    filelike = renpy.loader.load(self.filename, directory="images")
               ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/loader.py", line 698, in load
    raise FileNotFoundError("Couldn't find file '%s'." % name)
FileNotFoundError: Couldn't find file 'images/equipments/Miracle_boots.png'.

Windows-11-10.0.26120-SP0 AMD64
Ren'Py 8.4.1.25072401
Protectors 1.0
Tue Sep 16 17:04:58 2025
