I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 24, in script call
    call show_my_available_protectors(False)
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 24, in script call
    call show_my_available_protectors(False)
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
[Previous line repeated 6 more times]
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 34, in script call
    call see_expeditions_for_region(1)
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
[Previous line repeated 2 more times]
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
[Previous line repeated 7 more times]
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 37, in script call
    call see_expeditions_for_region(2)
  File "game/base_of_operations.rpy", line 83, in script
    call screen expedition_screen(regionNumber)
  File "game/classes.rpy", line 823, in startBossExpedition
    enemy = enemy_equip_equipments(enemy, rarity_number, target_class_name)
                                                         ^^^^^^^^^^^^^^^^^ 
UnboundLocalError: cannot access local variable 'target_class_name' where it is not associated with a value

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 24, in script call
    call show_my_available_protectors(False)
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 24, in script call
    call show_my_available_protectors(False)
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 26, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
[Previous line repeated 6 more times]
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 34, in script call
    call see_expeditions_for_region(1)
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
[Previous line repeated 2 more times]
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
[Previous line repeated 7 more times]
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 79, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 53, in script call
    call base_travel_menu()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 33, in script call
    call rest()
  File "game/places.rpy", line 35, in script call
    call base_travel_menu()
  File "game/places.rpy", line 15, in script call
    call go_to_computer()
  File "game/base_of_operations.rpy", line 5, in script call
    call see_expeditions(1)
  File "game/base_of_operations.rpy", line 37, in script call
    call see_expeditions_for_region(2)
  File "game/base_of_operations.rpy", line 83, in script
    call screen expedition_screen(regionNumber)
  File "renpy/ast.py", line 2231, in execute
    self.call("execute")
    ~~~~~~~~~^^^^^^^^^^^
  File "renpy/ast.py", line 2195, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/statements.py", line 379, in call
    return method(parsed, *args, **kwargs)
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/common/000statements.rpy", line 695, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/exports/statementexports.py", line 348, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/ui.py", line 304, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/core.py", line 2219, in interact
    repeat, rv = self.interact_core(
                 ~~~~~~~~~~~~~~~~~~^
        preloads=preloads,
        ^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )  # type: ignore
    ^                
  File "renpy/display/core.py", line 3302, in interact_core
    rv = root_widget.event(ev, x, y, 0)
         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "renpy/display/layout.py", line 1284, in event
    rv = i.event(ev, x - xo, y - yo, cst)
         ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/layout.py", line 1284, in event
    rv = i.event(ev, x - xo, y - yo, cst)
         ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/layout.py", line 1284, in event
    rv = i.event(ev, x - xo, y - yo, cst)
         ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/screen.py", line 805, in event
    rv = self.child.event(ev, x, y, st)
         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "renpy/display/layout.py", line 1284, in event
    rv = i.event(ev, x - xo, y - yo, cst)
         ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/layout.py", line 1508, in event
    rv = super(Window, self).event(ev, x, y, st)
         ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "renpy/display/layout.py", line 273, in event
    rv = d.event(ev, x - xo, y - yo, st)
         ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/layout.py", line 1284, in event
    rv = i.event(ev, x - xo, y - yo, cst)
         ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/layout.py", line 1284, in event
    rv = i.event(ev, x - xo, y - yo, cst)
         ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/layout.py", line 1284, in event
    rv = i.event(ev, x - xo, y - yo, cst)
         ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/behavior.py", line 1184, in event
    return handle_click(self.clicked)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "renpy/display/behavior.py", line 1107, in handle_click
    rv = run(action)
         ~~~^^^^^^^^
  File "renpy/display/behavior.py", line 411, in run
    return action(*args, **kwargs)
           ~~~~~~^^^^^^^^^^^^^^^^^
  File "renpy/common/00action_other.rpy", line 618, in __call__
    rv = self.callable(*self.args, **self.kwargs)
         ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/classes.rpy", line 823, in startBossExpedition
    enemy = enemy_equip_equipments(enemy, rarity_number, target_class_name)
                                                         ^^^^^^^^^^^^^^^^^ 
UnboundLocalError: cannot access local variable 'target_class_name' where it is not associated with a value

Windows-11-10.0.26120-SP0 AMD64
Ren'Py 8.4.1.25072401
Protectors 1.0
Mon Sep 22 18:07:11 2025
