I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 66, in script
    $ initializing_things()
  File "game/script.rpy", line 66, in <module>
    $ initializing_things()
      ~~~~~~~~~~~~~~~~~~~^^
  File "game/initializing_things.rpy", line 2824, in initializing_things
    initializing_expedition_bosses()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "game/expeditions/initializing_expedition_bosses.rpy", line 19, in initializing_expedition_bosses
    expeditions_bosses_base_data["The Mireborn Tyrant"] = BaseProtectorData(
                                                          ~~~~~~~~~~~~~~~~~^
        {
        ^
    ...<29 lines>...
        "Rusty Sword"
        ^^^^^^^^^^^^^
    )
    ^
TypeError: BaseProtectorData.__init__() missing 2 required positional arguments: 'evo2_unarmed_damage_type' and 'default_weapon'

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/script.rpy", line 66, in script
    $ initializing_things()
  File "renpy/ast.py", line 1187, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1260, in py_exec_bytecode
    exec(bytecode, globals, locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/script.rpy", line 66, in <module>
    $ initializing_things()
      ~~~~~~~~~~~~~~~~~~~^^
  File "game/initializing_things.rpy", line 2824, in initializing_things
    initializing_expedition_bosses()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "game/expeditions/initializing_expedition_bosses.rpy", line 19, in initializing_expedition_bosses
    expeditions_bosses_base_data["The Mireborn Tyrant"] = BaseProtectorData(
                                                          ~~~~~~~~~~~~~~~~~^
        {
        ^
    ...<29 lines>...
        "Rusty Sword"
        ^^^^^^^^^^^^^
    )
    ^
TypeError: BaseProtectorData.__init__() missing 2 required positional arguments: 'evo2_unarmed_damage_type' and 'default_weapon'

Windows-11-10.0.26120-SP0 AMD64
Ren'Py 8.4.1.25072401
Protectors 1.0
Tue Sep 23 11:38:05 2025
